forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apache',
  :git => "git://github.com/puppetlabs/puppetlabs-apache.git"
mod 'puppetlabs-apt',
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
mod 'puppetlabs-mongodb',
  # mongodb_pidfilepath scope issue when using managed repo. 
  #:git => "git://github.com/puppetlabs/puppetlabs-mongodb.git"
  :git => "git://github.com/xuwang/puppetlabs-mongodb.git"
mod 'puppetlabs-stdlib',
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
mod 'puppet-python',
  :git => "git://github.com/stankevich/puppet-python.git"
mod 'puppet-curl',
  :git => "git://github.com/alphagov/puppet-curl.git"
mod 'xuwang-sysupdate',
  :path => "/vagrant/puppet/modules.local/xuwang-sysupdate"
