#!/usr/bin/python
"""ppcli

Usage:
  ppcli.py new <DATA> 
  ppcli.py new (-f | --file) <FILE> 
  ppcli.py list
  ppcli.py get <ID | NAME>
  ppcli.py id NAME
  ppcli.py update <ID> <DATA>
  ppcli.py patch <ID> <DATA>
  ppcli.py delete <ID>
  ppcli.py (-h | --help)
  ppcli.py --version
  
Arguments:
  DATA  Data in json format. E.g. '[{"firstname": "barack", "lastname": "obama"}, {"firstname": "mitt", "lastname": "romney"}]'
  FILE  A data file in json format.
  ID    Persion's ID
  NAME  Persion's lastname
  
Options:
  -h --help     Show this screen.
  --version     Show version.
  -f --file     Data in file.
  
Examples:
  # create new people
  ppcli new '[{"firstname": "barack", "lastname": "obama"}, {"firstname": "mitt", "lastname": "romney"}]'
  
  # get a person's info
  ppcli get obama
  
  # delete a persion
  ppcli delete $(ppcli id 'obama')
    

"""
from docopt import docopt
import json
import pycurl
from StringIO import StringIO


if __name__ == '__main__':
    arguments = docopt(__doc__, version='ppcli 1.0')
    print(arguments)